### ISSUE TITLE
Sign Up Screen When Clicking on Full Name/ Email the background image shrinks

### ISSUE THREAD

**Issue by theindianappguy** [Sanaebadi97/Online-Fashion-Store#1]
I am attaching the images, I have tried surrounding the stack widget with Scrollable and ListView facing some issues 

![Screenshot_1576991454](https://user-images.githubusercontent.com/55942632/71317463-9c619280-24a7-11ea-943a-1aa5d8fb3b74.png)
![Screenshot_1576991458](https://user-images.githubusercontent.com/55942632/71317464-9cfa2900-24a7-11ea-927e-0ed590546724.png)

**Comment by shivanigupta19** [comment]
> I am attaching the images, I have tried surrounding the stack widget with Scrollable and ListView facing some issues
> 
> ![Screenshot_1576991454](https://user-images.githubusercontent.com/55942632/71317463-9c619280-24a7-11ea-943a-1aa5d8fb3b74.png)
> ![Screenshot_1576991458](https://user-images.githubusercontent.com/55942632/71317464-9cfa2900-24a7-11ea-927e-0ed590546724.png)

issue solved #1
Please close this issue

**Comment by theindianappguy** [comment]
Thanks

**Comment by shivanigupta19** [comment]
Please close the second one also and Thank you so much.
